# conf/config.yaml
defaults:
  - simulator: config
  - brain: config
  - _self_
  - override: buaa

monitoring:
  log_level: "INFO"
  log_dir: "logs/robot_brain_system_${now:%Y%m%d-%H%M%S}"
  log_file: "${monitoring.log_dir}/robot_brain_system.log"

skills:
  movetotarget:
    visualize: true
  objecttracking:
    visualize: false
    debug_save: false
    banned_cameras: ["camera_wrist", "camera_side","camera_top"]
  open_box:
    model_path: "assets/skills/press_rgb.pth"
    success_item: "box_open"
  grasp_spanner:
    model_path: "assets/skills/grasp_rgb.pth"
    success_item: "leave_spanner"
  move_box_to_suitable_position:
    success_item: "lift_eef"